# Generated by Django 3.2.15 on 2022-10-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.CharField(default='', max_length=10),
        ),
    ]
