# Generated by Django 3.2.15 on 2022-10-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221018_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.TextField(default=''),
        ),
    ]
