# Generated by Django 3.2.15 on 2022-10-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_country_state_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
    ]
