# Generated by Django 3.2.15 on 2022-10-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mrp', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('shipping_details', models.TextField()),
                ('return_details', models.TextField()),
                ('avg_rating', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
