# Generated by Django 3.2.15 on 2022-11-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimages_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='link',
        ),
    ]
