# Generated by Django 3.2.15 on 2022-11-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productimages_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteroptionitems',
            name='icon',
        ),
    ]
