# Generated by Django 3.2.15 on 2022-10-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20221008_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteroptionitems',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_option_items', to='products.filteroptions'),
        ),
    ]
