# Generated by Django 3.2.15 on 2022-11-09 06:45

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_filteroptionitems_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteroptionitems',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.filtericon_directory_path),
        ),
    ]
