# Generated by Django 3.2.15 on 2022-12-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20221212_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GoldPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='metal_purity',
        ),
        migrations.AlterField(
            model_name='product',
            name='diamond_weight',
            field=models.CharField(default='', max_length=5, verbose_name='Diamond Weight (ct)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gold_weight',
            field=models.CharField(default='', max_length=5, verbose_name='Gold Weight (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.CharField(default='', max_length=5, verbose_name='Gross Weight (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.CharField(default='', max_length=5, verbose_name='Net Weight (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.diamondpurity', verbose_name='Diamond Purity'),
        ),
        migrations.AddField(
            model_name='product',
            name='gold_purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.goldpurity', verbose_name='Gold Purity'),
        ),
    ]
