# Generated by Django 3.2.15 on 2022-12-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221212_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondpurity',
            name='making_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diamondpurity',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldpurity',
            name='making_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldpurity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
